### ISSUE TITLE
failed to load plugin aws_codedeploy Use of const in strict mode.

### ISSUE THREAD

**Issue by TravellingGuy** [flxbe/strider-aws-codedeploy#1]
Hi. I'm using strider v1.7.7 (latest release) and just tried to install the aws_codedeploy plugin (v0.1.4), but it fails to load and causes strider to go into a loop trying to start up again.

Here is the error:

```
/home/strider/strider/node_modules/strider-aws-codedeploy/worker.js:2
const tasks = require('./tasks');
^^^^^
2016-05-03T16:05:34.148Z - info: failed to load plugin aws_codedeploy Use of const in strict mode. SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/lib/index.js:324:29
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/lib/index.js:355:11
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/node_modules/async/lib/async.js:511:21
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/node_modules/async/lib/async.js:227:13
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/node_modules/async/lib/async.js:32:24)
    at async.each (/home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/node_modules/async/lib/async.js:110:9)
    at _asyncMap (/home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/node_modules/async/lib/async.js:226:9)
    at Object.map (/home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/node_modules/async/lib/async.js:204:23)
2016-05-03T16:05:34.149Z - error: [SyntaxError: Use of const in strict mode.; error loading plugin aws_codedeploy]
2016-05-03T16:05:34.149Z - error: Failed to load plugins
2016-05-03T16:05:34.149Z - info: Marking zombie jobs as finished...
2016-05-03T16:05:34.231Z - info: initalized static directories
2016-05-03T16:05:34.234Z - info: 0 zombie jobs marked as finished
2016-05-03T16:05:34.234Z - error: Strider seems to have been misconfigured - there are no available runner plugins. Please make sure all dependencies are up to date.
23559 died 1 null

```

**Comment by flxbe** [comment]
Hey. This looks like your node-version does not support ES6-features like 'const' and 'let'. Which version do you use?

In 0.10 and 0.12, you could try to start strider using the harmony-flag:
`node --harmony bin/strider`

Starting from node v4, it should work without any runtime-flags.

**Comment by TravellingGuy** [comment]
I am using node v0.10.25. I ran strider as per your suggestion and that seems to have worked around the initial issue, however now I'm getting a different error:

```
/home/strider/strider/node_modules/strider-aws-codedeploy/tasks/index.js:66
  config.artifactName = `${config.applicationName}_${config.deploymentGroup}_s
                        ^
2016-05-03T17:15:21.563Z - info: failed to load plugin aws_codedeploy Unexpected token ILLEGAL SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/strider/strider/node_modules/strider-aws-codedeploy/worker.js:2:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/lib/index.js:324:29
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/lib/index.js:355:11
    at /home/strider/strider/node_modules/strider-simple-runner/node_modules/strider-extension-loader/node_modules/async/lib/async.js:511:21
2016-05-03T17:15:21.563Z - error: [SyntaxError: Unexpected token ILLEGAL; error loading plugin aws_codedeploy]
```

**Comment by flxbe** [comment]
Again, Template Literals (that is, strings defined as `` instead of with '' or "") are a ES6 feature. Apparently, this is not available in node 0.10 and 0.12. There exist two possibilities to solve this issue:
- You change to a node-version, that supports these features (node 4.x and above)
- I replace all used features with downward-compatible syntax

How easy is it for you to upgrade your node-version?

**Comment by TravellingGuy** [comment]
node 0.10.25 is the default version installed on Ubuntu 14.04 LTS, so it may be likely that more people will run into this issue going forward (and submit issues here). From that perspective, it may be better for you to use backward-compatible syntax. I see node 4.x is the default in the new 16.04 LTS, though.

However, I'm simply testing strider at the moment, so it's no big deal for me to upgrade node to a newer release. Actually, I may just end up trying strider on 16.04 instead and go that route.

So, up to you what you want to do. :smile: Either way, personally I'll go with the upgrade route, so you can close this ticket.

Thanks for your help, appreciate it (I'm not familiar with node, so I never would have known it was a version issue).

**Comment by flxbe** [comment]
Ah, okay. I did not know, that node 0.10 is the default version on Ubuntu 14.04.

Personally, I prefer to use the new syntax-features. Since those will be compatible with 16.04, I would rather stick with the current version and just add an entry in the readme.

Anyway, thanks for using the plugin and reporting the issue!
