### ISSUE TITLE
"TypeError: Not a buffer" error during deploy

### ISSUE THREAD

**Issue by TravellingGuy** [flxbe/strider-aws-codedeploy#2]
I'm having an issue with the CodeDeploy plugin throwing a "TypeError: Not a buffer" error during the "Deploy to AWS ..." phase.

Here is the output:

```
# Start deployment ...
# Bundle aws artifact ...
$ mkdir aws_build
rm: cannot remove ‘aws_build’: No such file or directory
$ zip aws_build/my-project_prod_strider_artifact.zip . --recurse-paths --exclude aws_build/\* .git/\* --quiet
# Deploy to AWS ...
$
An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

Not a buffer

TypeError: Not a buffer
    at TypeError (native)
    at new Hmac (crypto.js:87:16)
    at Object.Hmac (crypto.js:85:12)
    at Object.hmac (/home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/util.js:396:24)
    at sign (/home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/signers/s3.js:165:28)
    at addAuthorization (/home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/signers/s3.js:57:26)
    at /home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/event_listeners.js:160:18
    at finish (/home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/config.js:299:7)
    at /home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/config.js:315:9
    at /home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/credentials.js:123:23
    at Credentials.refresh (/home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/credentials.js:148:5)
    at Credentials.get (/home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/credentials.js:121:12)
    at getAsyncCredentials (/home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/config.js:309:24)
    at Config.getCredentials (/home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/config.js:329:9)
    at Request.SIGN (/home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/event_listeners.js:141:26)
    at Request.callListeners (/home/strider/strider/node_modules/strider-aws-codedeploy/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
```

It appears (based on [this](http://stackoverflow.com/questions/24145508/typeerror-not-a-buffer-node-js-crypto-aws-sdk)) that it might be the secret key isn't being properly sent/used. I'm using Explicit credentials.

**Comment by flxbe** [comment]
Yes, your explanation seems to be correct. I will try to reproduce and fix that tomorrow, unfortunately I do not have enough time today.

**Comment by flxbe** [comment]
This should hopefully solve the issue. Let me know, if it works.

**Comment by TravellingGuy** [comment]
Awesome, it works! Thanks for you help on getting me up and going.
